apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backsvc
  name: backsvc
  namespace: ram
spec:
  ports:
  - name: 8085-8080
    port: 8085
    protocol: TCP
    targetPort: 8080
  selector:
    app: backsvc
  type: LoadBalancer
status:
  loadBalancer: {}
