apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontdep
  name: frontdep
  namespace: ram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontdep
    spec:
      containers:
      - image: raamriot/frontend:latest
        name: frontend
        ports:
        - containerPort: 8080
        resources: {}
status: {}
