apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontsvc
  name: frontsvc
  namespace: ram
spec:
  ports:
  - name: 8084-8080
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontsvc
  type: LoadBalancer
status:
  loadBalancer: {}
